version: 2

jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/aspnetcore-build:1.0-1.1
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore ./CIWorkflow.sln
      - run: dotnet build ./CIWorkflow.sln
      - run: dotnet test ./CIWorkflowTests/CIWorkflowTests.csproj
      - deploy:
          name: dockerhub
          command: ${DOCKER_HUB_TRIGGER}
